site_name: Growbotics AI Resources
site_url: https://growbotics-ai.github.io/resources/
repo_url: https://github.com/Growbotics-AI/resources
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.view
    - content.action.edit
  icon:
    edit: material/pencil 
    view: material/eye
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  favicon: images/favicon.ico
  logo: images/favicon-32x32.png

nav:
  - Welcome: index.md
  - Books: books.md
  - Conferences: conferences.md
  - Courses: courses.md
  - Podcasts: podcasts.md
  - Tools: tools.md
  - Useful Websites: websites.md
  - YouTube Channels: youtube.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Growbotics-AI
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Tomas0413
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/growbotics.ai
  manifest: images/site.webmanifest
  analytics:
    provider: google
    property: G-HCZ888XZLK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Growbotics-AI"  target="_blank" rel="noopener">Growbotics AI</a>